export const voices = [
  { label: "Juyoung" },
  { label: "Jessica" },
  { label: "Aditi" },
  { label: "Jane" },
  { label: "Jarvis" },
];

export const languages = [
  { label: "Korean", value: "ko-KR" },
  { label: "English", value: "en-US" },
  { label: "Spanish", value: "es-ES" },
  { label: "French", value: "fr-FR" },
  { label: "Italian", value: "it-IT" },
  { label: "Hindi", value: "hi-IN" },
  { label: "Chinese", value: "zh-CN" },
  { label: "Dutch", value: "nl-NL" },
  { label: "Turkish", value: "tr-TR" },
  { label: "Swedish", value: "sv-SE" },
  { label: "Indonesian", value: "id-ID" },
  { label: "Filipino", value: "fil-PH" },
  { label: "Japanese", value: "ja-JP" },
  { label: "Ukrainian", value: "uk-UA" },
  { label: "Greek", value: "el-GR" },
  { label: "Czech", value: "cs-CZ" },
  { label: "Finnish", value: "fi-FI" },
  { label: "Romanian", value: "ro-RO" },
  { label: "Russian", value: "ru-RU" },
  { label: "Danish", value: "da-DK" },
  { label: "Bulgarian", value: "bg-BG" },
  { label: "Malay", value: "ms-MY" },
  { label: "Slovak", value: "sk-SK" },
  { label: "Croatian", value: "hr-HR" },
  { label: "Classic Arabic", value: "ar-SA" },
  { label: "Tamil", value: "ta-IN" },
  { label: "Polish", value: "pl-PL" },
  { label: "German", value: "de-DE" },
  { label: "Portuguese", value: "pt-BR" },
];
